version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nutrigrow_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: db_name
      DB_USER: username
      DB_PASSWORD: password
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge